[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2

[[main]]
    identifier = "categories"
    name = "Categorias"
    url = "/categories"
    weight = 3
    
# Social Media Configuration

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://x.com/gustamms"
    weight = 1

[[social]]
    identifier = "instagram"
    name = "Instagram"
    url = "https://instagram.com/gustamms"
    weight = 2

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/gustamms"
    weight = 3